### ISSUE TITLE
empty qr string 

### ISSUE THREAD

**Issue by realyukii** [hansputera/gampang#7]
I tried logging in using the terminal, and got the following error:
```bash
/home/reyuki/Desktop/gampang/node_modules/qrcode/lib/core/qrcode.js:476
    throw new Error('No input text')
          ^

Error: No input text
    at Object.create (/home/reyuki/Desktop/gampang/node_modules/qrcode/lib/core/qrcode.js:476:11)
    at /home/reyuki/Desktop/gampang/node_modules/qrcode/lib/server.js:71:29
    at new Promise (<anonymous>)
    at render (/home/reyuki/Desktop/gampang/node_modules/qrcode/lib/server.js:69:12)
    at Object.toString (/home/reyuki/Desktop/gampang/node_modules/qrcode/lib/server.js:97:10)
    at se (/home/reyuki/Desktop/gampang/dist/index.js:1:2670)
    at $.launch (/home/reyuki/Desktop/gampang/dist/index.js:1:24706)
```

when I try to dig deeper into this error, I see that the qr string is empty and causes the above error

**Comment by hansputera** [comment]
lemme check it

**Comment by realyukii** [comment]
Thanks for the response @hansputera. the error is completely gone now, but it seems that the qrcode does not display nor does it show any error, is there an error that I don't know about or is there something I'm missing?
![image](https://user-images.githubusercontent.com/126035476/229305506-8b6cb425-e748-433c-81b1-3fb3dac40a5c.png)
